### ISSUE TITLE
ls is unpublished from npmjs

### ISSUE THREAD

**Issue by jidma** [awnist/ls#3]
The project has been unpublished from npmjs today as of 16/09/2020 at 17h

    $ npm install ls
    npm ERR! code ENOVERSIONS
    npm ERR! No valid versions available for ls

![image](https://user-images.githubusercontent.com/2295247/93386705-05700e00-f860-11ea-9ddf-035b73254df6.png)

**Comment by stripedpajamas** [comment]
was sad to discover this today :( very handy module.

**Comment by qoby** [comment]
That stinks, I didn't unpublish. Not sure what's going on, I contacted npm support and will update here.

Thanks for letting me know!

**Comment by soajetunmobi** [comment]
Hi, it's the same thing for yarn: https://registry.yarnpkg.com/ls/-/ls-0.2.1.tgz. We are getting `{
error: "Not found"
}`

![Screenshot 2020-09-18 at 09 20 38](https://user-images.githubusercontent.com/11750523/93574458-597a1000-f990-11ea-80ae-eca77baa8eaf.png)


Please how soon can this be resolved as this is blocking our code build pipeline?
Thanks.

**Comment by ethomson** [comment]
@qoby sorry about the trouble, the package was inadvertently unpublished.  😢  We've restored all the versions of `ls` and things should be working for your users again.  Many apologies for this problem.

**Comment by qoby** [comment]
Thanks @ethomson! Impressive responsiveness from support, and also appreciate you taking the time to reach out here.

**Comment by qoby** [comment]
Hey everyone, the package ls[1] had all its dependents wiped, and they
haven't been restored still. Looks like a bug?

[1]: https://www.npmjs.com/package/ls
